### ISSUE TITLE
Support for generating data models

### ISSUE THREAD

**Issue by altinnadmin** [Altinn/altinn2-convert#5]
This tool should be able to generate datamodel files based on the XSD from the TUL package.
The code used in Studio should be reused in some way.

## Tasks

- [ ] Generate datamodel files
- [x] Hook up layout components to the correct data model elements

**Comment by ivarne** [comment]
Second task is ✅,

**Comment by altinnadmin** [comment]
> Second task is ✅

@ivarne Excellent. Remember that you now can check these yourself and also merge PRs after QA ;)

**Comment by TheTechArch** [comment]
Do we want to generate from that XSD. Does not that have XSD = Nill stuff we don't want

**Comment by ivarne** [comment]
I don't know? The only difference I can see from the xsd (presumably downloaded) from SERES and the one in the TUL package is some differences in whitespace and attributte order and that the TUL package includes`<?xml version="1.0" encoding="UTF-8" standalone="no"?>` in the first line.

**Comment by RonnyB71** [comment]
This is about extracting the code we have in data modelling into it's own package and to run it as part of the migration tool ie. it's basically the same as uploading an XSD.

**Comment by ivarne** [comment]
Yea, we have 4 options (I think 🤔)

- Extract the code that converts xsd files to the other models we use (along with the initialization template for new apps) to a separate nuget package)
- Copy the relevant files and maintain them in both repos (convert is presumably short lived)
- reference relative paths so we assume altinn-studio and altinn-convert are always checked out next to each other (or git submodule)
- integrate (part of) convert into studio, so the models will be generated there. Maybe upload a zip from convert instead of just xsd?

**Comment by TheTechArch** [comment]
Maybe i remember it wrong then. Maybe it is in SBL we do this changes. Infopath does not support missing XML nodes so in Altinn 2 we populate nil nodes for complete xML. This causes a big amount of not needed XML storage in Altinn 2.

**Comment by ivarne** [comment]
I hope you do remember wrong, but thanks for raising the issue anyway. The issue at hand here, is if the xsd files in the infopath xsn packages from TUL are in fact equivalent to the xsd files downloaded from SERES that we usually upload in Altinn studio. It has nothing to do with `<element  xsi:nil="true"></element>` in the produced xml.

**Comment by altinnadmin** [comment]
> Yea, we have 4 options

Perhaps 5, we could expose the functionality as an API in Studio that convert then uses. Perhaps not optimal when considering performance and bulk operations.

> Infopath does not support missing XML nodes so in Altinn 2 we populate nil nodes for complete xML. 

Correct, but I think InfoPath does this nil-inserting automatically, affecting the actual XML that is saved, not the XSD.

*BUT*, there should be an alternate XSD generated somewhere with `minOccurs` set to zero to support validating/saving forms that are "incomplete"... @RogerKjaernsrod Do you remember?

**Comment by ivarne** [comment]
Yes, 5 it definitely is, but in addition to the speed penalty for bulk conversion, development would be somewhat annoying when you need to run studio locally in order to test changes. But maybe we get that api right the first time?

**Comment by RogerKjaernsrod** [comment]
If you create an InfoPath form from scratch without an existing xsd, then InfoPath will auto insert nillable="true" for elements with xsd types that cannot be empty (eg. integer, date).
If you create an InfoPath form based on an existing xsd, then you have to add nillable=true yourself to elements if you don't want them to be mandatory.

**Comment by SandGrainOne** [comment]
@altinnadmin I believe a part of the solution for the special "allow missing mandatory elements" rule we have in Altinn II is solved in the XsdValidator implementation we have.

**Comment by ivarne** [comment]
Bringing this discussion back to reality. Nobody seems to have done this exact thing before. Only way to make sure the xsds in the xsn files are equivalent to the xsds in SERES (and the datamoddels repo?) is to write a script to compare all of them. I have manually done a sample size of one for one of the old KRT xsds. Do you think this issue might only affect some cases?

**Comment by altinnadmin** [comment]
No. Ref. the info from both @SandGrainOne and @RogerKjaernsrod it seems like the xsds should be fine. They are also the XSDs we used when populating the data models in Studio. So I think we're good.

**Comment by ivarne** [comment]
@altinnadmin Then we need to make a decision on which approach we want to try first.

I'm leaning towards a combination of 2 and 3 (reference the template and copy/modify the model generating code), because it avoids a lot of work to refactor the existing code to work for both cases, If we are lucky, I'll end up with a separate project/DLL for the model generation that can be copied back and used in studio and used there. If not, it was more work than we're willing to put in. What do you think? What should the name of the C# class library be?

**Comment by altinnadmin** [comment]
Yeah, agree, sounds like a fine first approach.
First pri now is *momentum*, getting the converter up and running, and then copying the code makes sense.

And if we do relevant functional changes/fixes on "either side", we should create a PR to stay in sync, or as a minimum give a heads-up in the altinn2-convert slack channel. 

Sounds ok @RonnyB71 ?

**Comment by RonnyB71** [comment]
> Yeah, agree, sounds like a fine first approach. First pri now is _momentum_, getting the converter up and running, and then copying the code makes sense.
> 
> And if we do relevant functional changes/fixes on "either side", we should create a PR to stay in sync, or as a minimum give a heads-up in the altinn2-convert slack channel.
> 
> Sounds ok @RonnyB71 ?
Yep. We probably won't go through the trouble of extracting this on our side then, unless we see that maintenance becomes a problem. Staying in sync on this should be doable I think.

**Comment by ivarne** [comment]
@altinnadmin My current implementation for mapping `xPath` from altinn 2 to `dataModelBindings` in altinn 3 is 
![image](https://user-images.githubusercontent.com/131616/144371124-7afe2360-a5e1-4da8-a1f3-72ed4b464ae5.png)

Now that I'm looking at `*.metadata.json` for I see that the `.Replace('/', '.')` can be a lookup instead. Do you think there might be any value in that?

**Comment by altinnadmin** [comment]
If replace works fine I currently don't see a clear value. Do you?

**Comment by ivarne** [comment]
No, I just wanted to see if you knew any hidden things that might come up. Validation that the result actually match the model might be the only one, but that time would probably be better spent on a validation function in studio (and/or a startup task in the app template)

**Comment by ivarne** [comment]
After https://github.com/Altinn/altinn2-convert/pull/14 we also generate models from xsd in TULPACKAGE, so this issue is fully complete now.
